version: "3.9"

services:
  app:
    build: .
    container_name: enem_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enem.rule=Host(`enem.erikna.com`)"
      - "traefik.http.routers.enem.entrypoints=web, websecure"
      - "traefik.http.routers.enem.tls=true"
      - "traefik.http.routers.enem.tls.certresolver=production"
    networks:
      - web

networks:
  web:
    external: true
